sonar.projectKey=react-training-project
sonar.projectName=React Training Project
sonar.sources=frontend/src
sonar.tests=frontend/src/tests
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.tsx,**/*.test.ts
